name: foodshare
description: "A Flutter app to combat hunger and food waste by connecting surplus food donors with nearby shelters, volunteers, and community aid hubs."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: 3.15.1
  firebase_auth: 5.6.2
  cloud_firestore: 5.6.11
  firebase_messaging: 15.2.9
  firebase_storage: 12.4.9
  cloud_functions: 5.6.1
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  google_sign_in: ^6.1.6
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - web/icons/
