// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcjwP2AP1YekF3Urg-EJ5T743-5Jsnyyc',
    appId: '1:383740409419:web:6462e232a50cc99ef33fce',
    messagingSenderId: '383740409419',
    projectId: 'foodsharing-5777b',
    authDomain: 'foodsharing-5777b.firebaseapp.com',
    storageBucket: 'foodsharing-5777b.firebasestorage.app',
    measurementId: 'G-WY152K3N6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jsQlwU5j7lPkf5H_ULeeya1Sp4XoGm4',
    appId: '1:383740409419:android:673f9fa698a68023f33fce',
    messagingSenderId: '383740409419',
    projectId: 'foodsharing-5777b',
    storageBucket: 'foodsharing-5777b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3JK5d7bTSKdiIxgcTUeZM6Wmz0RjUYU',
    appId: '1:383740409419:ios:3956b68cd433464df33fce',
    messagingSenderId: '383740409419',
    projectId: 'foodsharing-5777b',
    storageBucket: 'foodsharing-5777b.firebasestorage.app',
    iosBundleId: 'com.nzyoka.foodsharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3JK5d7bTSKdiIxgcTUeZM6Wmz0RjUYU',
    appId: '1:383740409419:ios:3956b68cd433464df33fce',
    messagingSenderId: '383740409419',
    projectId: 'foodsharing-5777b',
    storageBucket: 'foodsharing-5777b.firebasestorage.app',
    iosBundleId: 'com.nzyoka.foodsharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcjwP2AP1YekF3Urg-EJ5T743-5Jsnyyc',
    appId: '1:383740409419:web:b828883d291ab73bf33fce',
    messagingSenderId: '383740409419',
    projectId: 'foodsharing-5777b',
    authDomain: 'foodsharing-5777b.firebaseapp.com',
    storageBucket: 'foodsharing-5777b.firebasestorage.app',
    measurementId: 'G-4QPRP4MFSY',
  );
}
